apiVersion: v1
kind: Service
metadata:
  # hangileri statefulsetler ile eslestrilmekte kullaniliyor ?
  name: geth
  namespace: geth
  labels:
    app: geth
spec:
  ports:
  - port: 8545
    name: node1
  - port: 8546
    name: node2
  - port: 8547
    name: node3
  clusterIP: 10.152.183.132

  selector:
    app: geth
