
apiVersion: v1
kind: Pod
metadata:
  namespace: geth
  name: alpine
  labels:
    app: alpine
spec:
  containers:
  - name: alpine
    image: alpine
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /root/.ethereum
      name: data2


  volumes:
  - name: data2
    persistentVolumeClaim:
      claimName: 'geth-pv-claim-dev'