# Persistance volumedaki dosyaları kontrol etmek için. İstenirse çalıştırılmayadabilir. FOR DEVS.
apiVersion: v1
kind: Pod
metadata:
  namespace: geth
  name: alpine
  labels:
    app: alpine
spec:
  containers:
  - name: alpine
    resources:              # Limitleri belirliyoruz
      requests:
        cpu: "0.25"
        memory: "300Mi"
      limits:
        cpu: ".5"
        memory: "375Mi"
    image: alpine
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /root/.ethereum
      name: data2


  volumes:
  - name: data2
    persistentVolumeClaim:
      claimName: 'geth-pv-claim-dev'