/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	bulutzincirv1alpha1 "bulutzincir/ethereum-operator/pkg/apis/bulutzincir/v1alpha1"
	versioned "bulutzincir/ethereum-operator/pkg/client/clientset/versioned"
	internalinterfaces "bulutzincir/ethereum-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "bulutzincir/ethereum-operator/pkg/client/listers/bulutzincir/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EthereumInformer provides access to a shared informer and lister for
// Ethereums.
type EthereumInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.EthereumLister
}

type ethereumInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewEthereumInformer constructs a new informer for Ethereum type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEthereumInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEthereumInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredEthereumInformer constructs a new informer for Ethereum type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEthereumInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BulutzincirV1alpha1().Ethereums(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BulutzincirV1alpha1().Ethereums(namespace).Watch(options)
			},
		},
		&bulutzincirv1alpha1.Ethereum{},
		resyncPeriod,
		indexers,
	)
}

func (f *ethereumInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEthereumInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *ethereumInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&bulutzincirv1alpha1.Ethereum{}, f.defaultInformer)
}

func (f *ethereumInformer) Lister() v1alpha1.EthereumLister {
	return v1alpha1.NewEthereumLister(f.Informer().GetIndexer())
}
