---
curl -k -X POST -H "Content-Type: application/yaml" \
-H "Authorization: Bearer <YourToken>" --data '
apiVersion: v1
kind: Pod
metadata:
  name: geth-app3
  labels:
    app: web
spec:
  containers:
    - name: geth2
      image: jozzy008/geth2:v0.0.1
      ports:
        - containerPort: 80
' "http://127.0.0.1:8080/api/v1/namespaces/default/pods"
