--- 
apiVersion: cert-manager.io/v1
kind: Issuer
metadata: 
  name: letsencrypt-prod
spec: 
  acme: 
    email: "ayb84870@gmail.com"
    http01: {}
    privateKeySecretRef: 
      name: letsencrypt-prod
    server: "https://acme-v02.api.letsencrypt.org/directory"