# WIP kullanma
apiVersion: v1
kind: PersistentVolume
metadata:
  name: geth-volume
  labels:
    type: local
spec:
  storageClassName: manual # bu ne ?
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/root/.ethereum"
    
