# WIP kullanma
apiVersion: v1
kind: PersistentVolume
metadata:
  name: geth-pv
  namespace: geth
  labels:
    type: local
spec:
  storageClassName: microk8s-hostpath # bu ne ?
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/root/.ethereum"
    
