apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geth-pv-claim
  namespace: geth
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi