kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ethereum-operator
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - bulutzincir.io
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ethereum-operator
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ethereum-operator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ethereum-operator
subjects:
- kind: ServiceAccount
  name: ethereum-operator
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ethereum-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ethereum-operator
  template:
    metadata:
      labels:
        app: ethereum-operator
    spec:
      serviceAccountName: ethereum-operator
      containers:
      - name: ethereum-operator
        image: localhost:32000/ethereum-operator:0.1
