/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "bulutzincir/ethereum-operator/pkg/apis/bulutzincir/v1alpha1"
	scheme "bulutzincir/ethereum-operator/pkg/client/clientset/versioned/scheme"
	ctx "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EthereumsGetter has a method to return a EthereumInterface.
// A group's client should implement this interface.
type EthereumsGetter interface {
	Ethereums(namespace string) EthereumInterface
}

// EthereumInterface has methods to work with Ethereum resources.
type EthereumInterface interface {
	Create(*v1alpha1.Ethereum) (*v1alpha1.Ethereum, error)
	Update(*v1alpha1.Ethereum) (*v1alpha1.Ethereum, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Ethereum, error)
	List(opts v1.ListOptions) (*v1alpha1.EthereumList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Ethereum, err error)
	EthereumExpansion
}

// ethereums implements EthereumInterface
type ethereums struct {
	client rest.Interface
	ns     string
}

// newEthereums returns a Ethereums
func newEthereums(c *BulutzincirV1alpha1Client, namespace string) *ethereums {
	return &ethereums{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the ethereum, and returns the corresponding ethereum object, and an error if there is any.
func (c *ethereums) Get(name string, options v1.GetOptions) (result *v1alpha1.Ethereum, err error) {
	result = &v1alpha1.Ethereum{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ethereums").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx.TODO()).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Ethereums that match those selectors.
func (c *ethereums) List(opts v1.ListOptions) (result *v1alpha1.EthereumList, err error) {
	result = &v1alpha1.EthereumList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ethereums").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do(ctx.TODO()).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested ethereums.
func (c *ethereums) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("ethereums").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch(ctx.TODO())
}

// Create takes the representation of a ethereum and creates it.  Returns the server's representation of the ethereum, and an error, if there is any.
func (c *ethereums) Create(ethereum *v1alpha1.Ethereum) (result *v1alpha1.Ethereum, err error) {
	result = &v1alpha1.Ethereum{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("ethereums").
		Body(ethereum).
		Do(ctx.TODO()).
		Into(result)
	return
}

// Update takes the representation of a ethereum and updates it. Returns the server's representation of the ethereum, and an error, if there is any.
func (c *ethereums) Update(ethereum *v1alpha1.Ethereum) (result *v1alpha1.Ethereum, err error) {
	result = &v1alpha1.Ethereum{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ethereums").
		Name(ethereum.Name).
		Body(ethereum).
		Do(ctx.TODO()).
		Into(result)
	return
}

// Delete takes name of the ethereum and deletes it. Returns an error if one occurs.
func (c *ethereums) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ethereums").
		Name(name).
		Body(options).
		Do(ctx.TODO()).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *ethereums) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ethereums").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do(ctx.TODO()).
		Error()
}

// Patch applies the patch and returns the patched ethereum.
func (c *ethereums) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Ethereum, err error) {
	result = &v1alpha1.Ethereum{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("ethereums").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do(ctx.TODO()).
		Into(result)
	return
}
